### ISSUE TITLE
Unable to install acodex-server in termux

### ISSUE THREAD

**Issue by pixelguy106** [bajrangCoder/acodex-server#6]
It's seems the new update cause major error on installation on acodex-server, before everything fine there is no any error when installing it but the new update cause to break the installation process, it seems it required the android_ndk now but before it doesn't need that. can you fix this issues.

```
$ npm i -g acodex-server
[##################] - reify:hono: timing reifyNode:node_modules/acod
> node-pty@1.0.0 install
> node-gyp rebuild

gyp info it worked if it ends with okming reifyNode:node_modules/acod
gyp info using node-gyp@10.0.1
gyp info using node@21.6.2 | android | arm
gyp info find Python using Python version 3.11.8 found at "/data/data/com.termux/files/usr/bin/python3"
[##################] / reify:hono: timing reifyNode:node_modules/acod
gyp info spawn /data/data/com.termux/files/usr/bin/python3odules/acod
gyp info spawn args [
gyp info spawn args '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/data/data/com.termux/files/home/.cache/node-gyp/21.6.2/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/21.6.2',
gyp info spawn args '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/21.6.2/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable android_ndk_path in binding.gyp while trying to load binding.gyp
gyp ERR! configure error ify:hono: timing reifyNode:node_modules/acod
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:271:18)
gyp ERR! stack at ChildProcess.emit (node:events:519:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 4.19.127-gfc2fca064b48-dirty
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty
gyp ERR! node -v v21.6.2
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-02-22T14_21_15_030Z-debug-0.log
```

**Comment by keremms** [comment]
I'm having the same problem too, please fix it

**Comment by deviaze** [comment]
Same issue here; failed to launch and now fails to reinstall.

**Comment by bajrangCoder** [comment]
Try this 

```shell
cd /data/data/com.termux/files/usr/lib/node_modules
npm i node-pre-gyp rebuild
pkg install nodejs
pkg install nodejs-lts
npm i -g acodex-server
```
> Run the commands
Issue: https://github.com/nodejs/node-gyp/issues/508

**Comment by pixelguy106** [comment]
> Try this
> 
> ```shell
> cd /data/data/com.termux/files/usr/lib/node_modules
> npm i node-pre-gyp rebuild
> pkg install nodejs
> pkg install nodejs-lts
> npm i -g acodex-server
> ```
> 
> > Run the commands
> > Issue: [nodejs/node-gyp#508](https://github.com/nodejs/node-gyp/issues/508)

![Screenshot_20240224-100126](https://github.com/bajrangCoder/acodex-server/assets/112818755/c046aea3-69f9-4f9f-8a3d-3a611a09ab85)

**Comment by deviaze** [comment]
> Try this 
> 
> ```shell
> cd /data/data/com.termux/files/usr/lib/node_modules
> npm i node-pre-gyp rebuild
> pkg install nodejs
> pkg install nodejs-lts
> npm i -g acodex-server
> ```
> > Run the commands
> Issue: https://github.com/nodejs/node-gyp/issues/508

Also failed here:
```shell
cd /data/data/com.termux/files/usr/lib/node_modules
npm i node-pre-gyp rebuild
pkg install nodejs
pkg install nodejs-lts
npm i -g acodex-server
npm WARN deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

added 70 packages, and removed 238 packages in 878ms

3 packages are looking for funding
  run `npm fund` for details
Checking availability of current mirror:
[*] https://mirror.fcix.net/termux/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (21.6.2-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Checking availability of current mirror:
[*] https://mirror.fcix.net/termux/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  nodejs
The following NEW packages will be installed:
  nodejs-lts
0 upgraded, 1 newly installed, 1 to remove and 2 not upgraded.
Need to get 9873 kB of archives.
After this operation, 5796 kB disk space will be freed.
Do you want to continue? [Y/n] Y
Get:1 https://mirror.fcix.net/termux/termux-main stable/main aarch64 nodejs-lts aarch64 20.11.1-1 [9873 kB]
Fetched 9873 kB in 1s (6860 kB/s)
(Reading database ... 30761 files and directories currently installed.)
Removing nodejs (21.6.2-1) ...
dpkg: warning: while removing nodejs, directory '/data/data/com.termux/files/usr/lib/node_modules' not empty so not removed
Selecting previously unselected package nodejs-lts.
(Reading database ... 27961 files and directories currently installed.)
Preparing to unpack .../nodejs-lts_20.11.1-1_aarch64.deb ...
Unpacking nodejs-lts (20.11.1-1) ...
Setting up nodejs-lts (20.11.1-1) ...
[#################.] - reify:node-pty: timing reifyNode:node_
> node-pty@1.0.0 install
> node-gyp rebuild

gyp info it worked if it ends with okming reifyNode:node_modu
gyp info using node-gyp@10.0.1
gyp info using node@20.11.1 | android | arm64
gyp info find Python using Python version 3.11.8 found at "/data/data/com.termux/files/usr/bin/python3"
[##################] / reify:hono: timing reifyNode:node_modu
gyp http GET https://nodejs.org/download/release/v20.11.1/node-v20.11.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v20.11.1/node-v20.11.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v20.11.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v20.11.1/SHASUMS256.txt
gyp info spawn /data/data/com.termux/files/usr/bin/python3odu
gyp info spawn args [
gyp info spawn args '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/data/data/com.termux/files/home/.cache/node-gyp/20.11.1/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/20.11.1',
gyp info spawn args '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/20.11.1/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: Undefined variable android_ndk_path in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:271:18)
gyp ERR! stack at ChildProcess.emit (node:events:518:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 5.15.94-android13-8-27763874-abS911U1UES2BXAD
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty
gyp ERR! node -v v20.11.1
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-02-24T02_03_46_644Z-debug-0.log
```
(image upload failed (thanks github mobile))

**Comment by Haerbin23456** [comment]
Relate to issue termux/termux-packages#20717

**Comment by bajrangCoder** [comment]
Try this solution: https://github.com/bajrangCoder/acode-plugin-acodex/issues/56#issuecomment-1968814723

**Comment by pixelguy106** [comment]
It installed but a error thrown when I try to use the acodex-server
![Screenshot_20240228-200753](https://github.com/bajrangCoder/acodex-server/assets/112818755/83e2922a-b1db-4ee2-bc17-9c37c583fb6e)

**Comment by bajrangCoder** [comment]
Ahh, there is a small bug in server , within an hour I am gonna publish a patch for it.

Thanks for Reporting!

**Comment by daniuwo** [comment]
> Ahh, there is a small bug in server , within an hour I am gonna publish a patch for it.
> 
> Thanks for Reporting!

Has it been fixed

**Comment by ghost** [comment]
> > Ahh, there is a small bug in server , within an hour I am gonna publish a patch for it.
> > Thanks for Reporting!
> 
> Has it been fixed

[Not yet](https://github.com/bajrangCoder/acodex-server/commits/main/)

**Comment by bajrangCoder** [comment]
> > Ahh, there is a small bug in server , within an hour I am gonna publish a patch for it.
> > Thanks for Reporting!
> 
> Has it been fixed

Yes, Update your `acodex-server` to `v1.1.4`

Using :
```bash
npm update -g acodex-server
```

**Comment by ghost** [comment]
![Screenshot_20240301-073703_Termux](https://github.com/bajrangCoder/acodex-server/assets/113766442/aceedbb5-2771-471b-816b-44e673a74110)
It worked, thanks

**Comment by harsha1-2-3** [comment]
It's working bajrangCoder thanks for the instant support 🙂.Keep Inspiring.

**Comment by bajrangCoder** [comment]
Glad to see 🥹🥹

**Comment by pixelguy106** [comment]
Thank you @bajrangCoder for fixing the bugs, you're truly a Chad 🗿🗿🗿

![Screenshot_20240301-150203](https://github.com/bajrangCoder/acodex-server/assets/112818755/91b5e387-6a52-42c6-a1e8-6fd32d234f44)
