### ISSUE TITLE
I got an error code: 'ERR_DLOPEN_FAILED'

### ISSUE THREAD

**Issue by devsanthoshmk** [bajrangCoder/acodex-server#7]
Please help to solve this issue:

innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/unixTerminal.js
- /data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/index.js
- /data/data/com.termux/files/usr/lib/node_modules/acodex-server/terminalServer.js
- /data/data/com.termux/files/usr/lib/node_modules/acodex-server/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/unixTerminal.js',
    '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/index.js',
    '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/terminalServer.js',
    '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/index.js'
  ]
}
/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/unixTerminal.js:40
        throw outerError;
        ^

Error: dlopen failed: cannot locate symbol "_ZN2v812api_internal18GlobalizeReferenceEPNS_8internal7IsolateEPm" referenced by "/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/build/Release/pty.node"...
    at Module._extensions..node (node:internal/modules/cjs/loader:1475:18)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/unixTerminal.js:29:11)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v21.6.2

**Comment by bajrangCoder** [comment]
Try to reinstall termux or provide more context about your environment

**Comment by devsanthoshmk** [comment]
> Try to reinstall termux or provide more context about your environment 

Thank you for your response now the issue is solved after acode update
